#cloud-config

runcmd:
  # ensure package lists are updated properly
  - sudo apt update && sudo apt upgrade -y

  # ensure SSH is installed
  - sudo apt install -y openssh-server

  # install required packages
  - sudo apt install -y git
  - sudo apt install -y python-is-python3
  - sudo apt install -y xauth
  - sudo apt install -y x11-apps
  - sudo apt install -y mininet
  - sudo apt install -y traceroute
  - sudo apt install -y python3-netaddr
  - sudo apt install -y dnsutils
  - sudo apt install -y lsof
  - sudo apt install -y firefox
  - sudo apt install -y xterm
  - sudo apt install -y nscd
  - echo "[cloud-init] All packages installed"

  # enable X11 forwarding
  - sudo test -f /etc/ssh/sshd_config && sudo sed -i 's/#X11Forwarding no/X11Forwarding yes/' /etc/ssh/sshd_config
  - echo "[cloud-init] X11Forwarding enabled in SSH config"
  - sudo test -f /etc/ssh/sshd_config && sudo sed -i 's/#X11DisplayOffset 10/X11DisplayOffset 10/' /etc/ssh/sshd_config
  - echo "[cloud-init] X11DisplayOffset configured"
  - sudo test -f /etc/ssh/sshd_config && sudo sed -i 's/#X11UseLocalhost yes/X11UseLocalhost yes/' /etc/ssh/sshd_config
  - echo "[cloud-init] X11UseLocalhost configured"

  # restart SSH
  - sudo systemctl restart ssh
  - echo "[cloud-init] SSH service restarted"

  # set up X11 auth
  - echo 'export XAUTHORITY=$HOME/.Xauthority' >> $HOME/.profile
  - echo "[cloud-init] X11 authorization set up"

  # clean up stuff
  - sudo apt clean && sudo apt autoclean
  - echo "[cloud-init] Cleaned up system"
